# Generated by Django 5.0.4 on 2024-06-20 16:27

from django.db import migrations


def set_price(apps, schema_editor):
    MULTIPLY_PRICE = 120
    smartphone_model = apps.get_model('main_app', 'Smartphone')

    for smartphone in smartphone_model.objects.all():
        smartphone.price = len(smartphone.brand) * MULTIPLY_PRICE
        smartphone.save()


def set_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')

    for smartphone in smartphone_model.objects.all():
        if smartphone.price >= 750:
            smartphone.category = "Expensive"
        else:
            smartphone.category = "Cheap"

        smartphone.save()


def set_category_and_price(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)


def revserse_code(apps, scema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    smartphones = smartphone_model.objects.all()

    default_price = smartphone_model._meta.get_field('price').default
    default_category = smartphone_model._meta.get_field('category').default

    for smartphone in smartphones:
        smartphone.price = default_price
        smartphone.category = default_category


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0014_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_category_and_price, reverse_code=revserse_code)
    ]
