# Generated by Django 5.0.4 on 2024-06-20 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_item'),
        ('main_app', '0012_migrate_item_rarity'),
    ]

    operations = [
    ]
