"""Added Song music_file_data

Revision ID: 0f7b2dea1508
Revises: 3fafda9e2902
Create Date: 2024-09-18 18:50:01.396300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f7b2dea1508'
down_revision: Union[str, None] = '3fafda9e2902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('albums')
    op.drop_table('songs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('song_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('music_file_data', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('album_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], name='songs_album_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='songs_pkey')
    )
    op.create_table('albums',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('album_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='albums_pkey'),
    sa.UniqueConstraint('album_name', name='albums_album_name_key')
    )
    # ### end Alembic commands ###
