# Generated by Django 5.1 on 2024-08-19 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruit',
            old_name='Image_url',
            new_name='image_url',
        ),
    ]
