# Generated by Django 5.0.4 on 2024-06-20 12:40

from django.db import migrations


def set_item_rarity(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')

    items = item_model.objects.all()

    for item in items:
        if item.price <= 10:
            item.rarity = "Rare"
        elif 11 >= item.price or 20 <= item.price:
            item.rarity = "Very Rare"
        elif 21 >= item.price or 30 <= item.price:
            item.rarity = "Extremely Rare"
        elif item.price >= 31:
            item.rarity = "Mega Rare"

    item_model.objects.bulk_update(items, ["rarity"])


def set_item_rarity_to_default(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')
    item_default_rarity = item_model._meta.get_field("rarity").default
    items = item_model.objects.all()

    for item in items:
        item.rarity = item_default_rarity

    item_model.objects.bulk_update(items, ["rarity"])


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0010_migrate_age_group'),
    ]

    operations = [
        migrations.RunPython(set_item_rarity, reverse_code=set_item_rarity_to_default)
    ]
