"""Update Recipe model

Revision ID: f963cdad34e3
Revises: ee1993b1ea4a
Create Date: 2024-08-13 19:14:47.997604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f963cdad34e3'
down_revision: Union[str, None] = 'ee1993b1ea4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('instructions', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'instructions')
    # ### end Alembic commands ###
