"""Added user and post models with relationship

Revision ID: 086858d18c9d
Revises: 5f8c9c4cd50a
Create Date: 2024-08-12 20:12:02.879154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '086858d18c9d'
down_revision: Union[str, None] = '5f8c9c4cd50a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companies')
    op.add_column('employees', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'city_id')
    op.create_table('companies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='companies_pkey')
    )
    # ### end Alembic commands ###
