# Generated by Django 5.0.6 on 2024-06-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0002_alter_employee_email_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="last_edit_on",
            new_name="last_edited_on",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="works_full_name",
            new_name="works_full_time",
        ),
        migrations.RemoveField(
            model_name="department",
            name="employee_count",
        ),
        migrations.AddField(
            model_name="department",
            name="employees_count",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Employees Count"
            ),
        ),
    ]
