# Generated by Django 5.0.4 on 2024-07-09 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_driver_drivinglicence'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrivingLicence',
            new_name='DrivingLicense',
        ),
    ]
